### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LuisaGa9** [nghorbani/human_body_prior#55]
Hi guys
It presented to me this error:

Processing: DATA_FOLDER/images/ariba.jpg
Traceback (most recent call last):
  File "smplifyx/main.py", line 272, in <module>
    main(**args)
  File "smplifyx/main.py", line 262, in main
    **args)
  File "/home/luisa/vsmpl2/programas/smplify-x/smplifyx/fit_single_frame.py", line 188, in fit_single_frame
    vposer, _ = load_vposer(vposer_ckpt, vp_model='snapshot')
  File "/home/luisa/vsmpl2/lib/python3.6/site-packages/human_body_prior/tools/model_loader.py", line 56, in load_vposer
    ps, trained_model_fname = expid2model(expr_dir)
  File "/home/luisa/vsmpl2/lib/python3.6/site-packages/human_body_prior/tools/model_loader.py", line 31, in expid2model
    best_model_fname = sorted(glob.glob(os.path.join(expr_dir, 'snapshots', '*.pt')), key=os.path.getmtime)[-1]
IndexError: list index out of range

Could you help me with this?

**Comment by urs-waldmann** [comment]
I have the same problem. I guess we miss the vposer checkpoints. But where/how can we get them?

**Comment by LuisaGa9** [comment]
> 

Thank you so much
